config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :organizations do
    resources :events, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :events, only: [:index]
  resources :events, only: [:show] do
    resources :bookmarks, only: [:create, :destroy]
  end
  resources :timeslots do
    resources :arrangements, only: [:new, :edit, :show, :create, :update, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :edit, :show, :create, :update] do
    resources :managed_organizations, only: [:index]
  end
  resources :welcomes, only: [:index]
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get '/welcome' => 'welcomes#index'
  get '/login' => 'sessions#new'
  delete '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get 'mailbox/inbox' => "mailboxes#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailboxes#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailboxes#trash", as: :mailbox_trash

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  # this guide was integral to building this controller
  # http://josephndungu.com/tutorials/private-inbox-system-in-rails-with-mailboxer


  def new
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:notice] = "Your message was sent!"
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user)
    conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply was sent!"
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end

  private

  def message_params
    params.require(:message).permit(:body, :subject)
  end

  def conversation_params
    params.require(:conversation).permit(:subject, :body, recipients:[])
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<% if conversation.is_unread?(current_user) %>
  <div class="convo-box unread" data-url="<%= conversation_url(conversation) %>">
<% else %>
  <div class="convo-box" data-url="<%= conversation_url(conversation) %>">
<% end %>
    <p class="convo"><strong>Subject: <%= conversation.subject %></strong> | Last message by: <%= conversation.messages.last.sender.name %></p>
    <p class="convo">"<%= truncate conversation.messages.last.body, length: 50 %>"</p>
    <small><%= conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small><br>
  </div>

app/views/conversations/_form.html.erb
<div class="new-convo">
  <%= form_for :conversation, url: :conversations, html: { class: "conversation" } do |f| %>
    <%= f.label :recipients %>
    <%= f.select(:recipients, User.all.collect { |p| [ p.name, p.id ] }, {selected: params[:recipients]}, {multiple: true,  class: 'select', id: "recipient-select" }) %>
    <div>
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject" %>
    </div>
    <div>
      <%= f.label :message %>
      <%= f.text_area :body %>
    </div>

    <%= f.submit "Send Message", class: "button radius" %>

  <% end %>
</div>

app/views/conversations/_messages.html.erb
<div class="all-receipts">
  <% @receipts.reverse.each do |receipt| %>
    <% message = receipt.message %>
    <% if message.sender == current_user %>
      <% classes = "one-message recipient-aligned" %>
    <% else %>
      <% classes = "one-message" %>
    <% end %>
    <div class="<%= classes %>" >
      <p>Sender: <%= message.sender.name %></p>
      <p><%= message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></p><br>
      <p><%= message.body %></p>
    </div>
  <% end %>
</div>

app/views/conversations/new.html.erb
<%= render partial: 'mailboxes/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<div class="mailbox-head large-12 columns">
  <h1>Conversation Subject: "<%= conversation.subject %>"</h1>
</div>
<div class="large-12 columns">
  <ul class="right">
    <%= link_to "New message", new_conversation_path, class: "button radius" %>
    <% if conversation.is_trashed?(current_user) %>
      <%= link_to "Untrash", untrash_conversation_path(conversation), class: "button radius", method: :post %>
    <% else %>
      <%= link_to 'Trash this conversation', trash_conversation_path(conversation), class: "button radius", method: :post, data: {confirm: "Do you want to move this to trash?"} %>
    <% end %>
  </ul>
</div>


<div class="large-2 small-3 columns">
  <%= render 'mailboxes/folders' %>
</div>

<div class="large-10 small-9 columns">
  <%= render partial: 'messages' %>
</div>
<div>
  <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
  <div>
    <%= f.text_area :body, placeholder: "Type your reply", rows: 4, class: "large-10 columns right reply-box" %>
  </div>
  <div class="large-12 columns">
    <%= f.submit "Reply", class: "button radius right reply-button" %>
  </div>
  <% end %>
</div>