config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :organizations do
    resources :events, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :events, only: [:index]
  resources :events, only: [:show] do
    resources :bookmarks, only: [:create, :destroy]
  end
  resources :timeslots do
    resources :arrangements, only: [:new, :edit, :show, :create, :update, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :edit, :show, :create, :update] do
    resources :managed_organizations, only: [:index]
  end
  resources :welcomes, only: [:index]
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get '/welcome' => 'welcomes#index'
  get '/login' => 'sessions#new'
  delete '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get 'mailbox/inbox' => "mailboxes#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailboxes#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailboxes#trash", as: :mailbox_trash

end

app/models/event.rb
class Event < ActiveRecord::Base
  mount_uploader :event_image, ImageUploader
	has_many :timeslots, dependent: :destroy
  accepts_nested_attributes_for :timeslots, reject_if: :all_blank, allow_destroy: true
	has_many :arrangements, through: :timeslots
  has_many :bookmarks, dependent: :destroy
  belongs_to :organization
  has_and_belongs_to_many :interests
  has_and_belongs_to_many :skills

  geocoded_by :location
  after_validation :geocode

  # Comments reference the method directly below the comment.
  # Some of the later methods have performance implications that may not scale.
  # I'd like to refactor to use more SQL statements in the future to improve performance.
  # Currently there are no validations as the act of event creation was lower priority in our
  # project plan.

  # ---

  # Finds event start time by checking start time of the earliest timeslot

  def start_time
  	self.timeslots.order(start_time: :asc).first.start_time.localtime
  end

  # finds event end time by checking end time of the latest time slot

  def end_time
  	self.timeslots.order(end_time: :asc).last.end_time.localtime
  end

  # returns a collection of only the events in the future

  def self.future
    joins(:timeslots).where("timeslots.start_time >= '#{Time.now}'").distinct
  end

  # total capacity for all of an event's timeslots added together

  def capacity
    self.timeslots.sum('capacity')
  end

  # For each timeslot, counts the number of arrangements and increments the total arrangements
  # and then returns the total.

  def total_volunteers
    currently_filled = 0
    self.timeslots.each do |timeslot|
      currently_filled += timeslot.arrangements.count
    end
    return currently_filled
  end

  # returns a % for the total volunteers progress bar to use

  def progress
    return (self.total_volunteers.to_f / self.capacity) * 100
  end

  # Class level method - returns a collection of the future events ordered by start_time.
  # In current form this does not return an active record association.

  def self.order_by_start_time
    events_and_times = future.sort_by do |event|
      event.start_time
    end
  end

  # returns an array of matches of an event's interests and a user's interests

  def match_interests(user)
    self.interests & user.interests
  end

  # returns an array of matches of an event's skills and a user's interests

  def match_skills(user)
    self.skills & user.skills
  end

  # returns a ranking asigned to an event by multiplying the interest match value * a weighting

  def interest_rank(user, weight)
    self.match_interests(user).count * weight.to_f
  end

  # returns a ranking asigned to an event by multiplying the skill match value * a weighting

  def skill_rank(user, weight)
    self.match_skills(user).count * weight.to_f
  end

  # returns a total ranking asigned to an event by adding the interest and skill ranks

  def total_rank(user, interest_weight, skill_weight)
    interest_rank(user, interest_weight) + skill_rank(user, skill_weight)
  end

  # Class level method - uses the "total rank" for an event to filter the events in order
  # of highest ranking first. Returns an array rather than an active record association so
  # could be improved.

  def self.filter_for_user(user, interest_weight, skill_weight)
    sorted_events = future.sort_by do |event|
      event.total_rank(user, interest_weight, skill_weight)
    end.reverse
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]
  before_action :get_event, only: [:show, :edit, :update, :destroy]
  before_action :get_organization, only: [:new, :edit, :create, :update, :destroy]
  before_action :get_interests, only: [:new, :edit]
  before_action :get_skills, only: [:new, :edit]
  before_action :is_event_coordinator?, only: [:new, :edit, :create, :update, :destroy]
  layout :indexlayout, only: [:index]

  def new
    @event = @organization.events.build
  end

  def create
    @event = @organization.events.build(event_params)
    if @event.save
      redirect_to event_path(@event), notice: "Successfully created a new event!"
    else
      flash[:alert] = "Sorry, your event could not be created"
      render :new
    end
  end

  def index
    if params[:q] == nil
      if params[:filter]
        case params[:filter]
        when "Event Date (ascending)"
          @events = Event.order_by_start_time
        when "Match my Interests"
          @events = Event.filter_for_user(current_user, 1, 0)
        when "Match my Skills"
          @events = Event.filter_for_user(current_user, 0, 1)
        when "Match my Interests AND Skills"
          @events = Event.filter_for_user(current_user, 0.6, 0.4)
        end
      else
        @events = Event.order_by_start_time
      end
    else
      @events = @q.result.includes(:interests, :skills).uniq
    end

    respond_to do |format|
      format.js
      format.html
    end
  end

  def show
    @bookmark = @event.bookmarks.build
  end


  def edit
  end

  def update
    if @event.update_attributes(event_params)
      if @event.arrangements.any?
        EventMailer.modified_email(@event).deliver_now
      end
      redirect_to event_path(@event), notice: "Successfully updated #{@event.name}."
    else
      flash[:alert] = "There was a problem saving your changes."
      render :edit
    end
  end

  def destroy
    if @event.destroy
      if @event.arrangements.any?
        EventMailer.deleted_email(@event).deliver_now
      end
      redirect_to user_managed_organizations_path(current_user), notice: "Event cancelled"
    else
      flash[:alert] = "Something went wrong, please try again."
      render :show
    end
  end

  private

  def event_params
    params.require(:event).permit(
      :name, :location, :description, :role, :event_image, :event_image_cache,
      timeslots_attributes: [:id, :start_time, :end_time, :capacity, :_destroy],
      :interest_ids => [], :skill_ids => []
    )
  end

  def get_event
    @event = Event.find(params[:id])
  end

  def get_organization
    @organization = Organization.find(params[:organization_id])
  end

  def get_skills
    @interests = Interest.all
  end

  def get_interests
    @skills = Skill.all
  end

  def is_event_coordinator?
    get_organization
    unless current_user == @organization.event_coordinator || current_user.admin
      redirect_to events_path, alert: "Invalid user permissions to access that page"
    end
  end

  def indexlayout
    if 'index'
      'indexlayout'
    else
      'layout'
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="event">
  <div class="large-4 medium-6 small-12 columns">
    <ul class="pricing-table active-tb shadow mrgn-20-top">
      <li class="title"><span id="event_name"><%= link_to event.name, event_path(event) %></span><br/><span id="event_role"><%= link_to event.role, event_path(event) %>
      <%= render partial: 'bookmarks/form', locals: { event: event, bookmark: Bookmark.new } %></span>
      <li class="event-image"><%= image_tag event.event_image.url(:mobile) if event.event_image.present? %></li>
      <li class="bullet-item" id="org_name"><%= link_to event.organization.name, organization_path(event.organization) %></li>
      <li class="bullet-item"><%= event.start_time.strftime("%b %d, %Y | %I:%M %p") %> - <%= event.end_time.strftime("%I:%M %p") %></li>

      <li class="bullet-item"><%= event.location %></li>
      <div id="timeslot-list">
        <li class="bullet-item"><p class="choose-a-time">Choose a time to volunteer</p>
          <ul class="button-group radius">
            <li>
              <a href="#" ><%= render partial: 'timeslots/timeslot', collection: event.timeslots.order(start_time: :asc) %></a>
            </li>
          </ul>
        </li>
        <li>
          <small><%= event.total_volunteers %> / <%= event.capacity %> Volunteer Spots Filled</small>
          <div class="progress secondary alert success radius">
              <span class="meter" style="width: <%= event.progress %>%"></span>
          </div>
        </li>
      </div>
       </ul>
    </div>
</div>

app/views/events/_filter_buttons.html.erb
<button href="#" data-dropdown="drop1" aria-controls="drop1" aria-expanded="false" class="button radius dropdown">
  <% if params[:filter] %>
    <%= params[:filter] %>
  <% else %>
    Filter Events
  <% end %>
</button><br>
<ul id="drop1" data-dropdown-content class="f-dropdown" aria-hidden="true">
  <% options = ["Event Date (ascending)"] %>
  <% if current_user.interests.any? && current_user.skills.any? %>
    <% options << "Match my Interests" << "Match my Skills" << "Match my Interests AND Skills" %>
  <% elsif current_user.interests.any? %>
    <% options << "Match my Interests" %>
  <% elsif current_user.skills.any? %>
    <% options << "Match my Skills" %>
  <% end %>
  <% options.each_with_index do |option| %>
    <li><%= link_to option, events_path(filter: option), remote: true %></li>
  <% end %>
</ul>

app/views/events/_form.html.erb
<%= form_for [@organization, @event] do |f| %>
  <div class="event-details-form">
    <h2>Event Details</h2>
    <%= f.label :name %><br/>
    <%= f.text_field :name, placeholder: "Enter the event's name." %>
    <%= f.label :description %><br/>
    <%= f.text_area :description, placeholder: "Enter a brief description of the event." %>
    <%= f.label :location %><br/>
    <%= f.text_field :location, placeholder: "Enter the address where the event takes place." %>
    <%= f.label :role %><br/>
    <%= f.text_field :role, placeholder: "Enter the role the volunteer is required for." %>
    <%= f.label :event_image %><br/>
    <%= f.file_field :event_image %>
    <%= f.hidden_field :event_image_cache %>
  </div>
  <div class="event-timeslots-form">
    <h2>Add Timeslots</h2>
    <p>What times do you require volunteers for this role and how many people do you need for each time?</p>
    <div class="fields-for">
      <%= link_to_add_association "Add new timeslot", f, :timeslots %>
      <%= f.fields_for :timeslots do |timeslot| %>
        <%= render 'timeslot_fields', :f => timeslot %>
      <% end %>
    </div>
  </div>
  <div class="event-interests-form">
    <h2>Event Interests</h2>
    <p>What interests are associated with your event?</p>
    <%= f.collection_select( :interest_ids, @interests, :id, :name, {},
    { multiple: true, class: 'select' })  %>
  </div>
  <div class="event-skills-form">
    <h2>Role Skills</h2>
    <p>What skills will a volunteer exercise in this role?</p>
    <%= f.collection_select( :skill_ids, @skills, :id, :name, {},
    { multiple: true, class: 'select' }) %>
  </div>
  <div class="submit">
    <%= f.submit class: 'button radius' %>
  </div>
<% end %>

app/views/events/_timeslot_fields.html.erb
<div class="nested-fields">
	<br/>
	<p>Timeslot</p>
	<%= f.label :start_time %><br/>
	<%= f.datetime_local_field :start_time %><br/>
	<%= f.label :end_time %><br/>
	<%= f.datetime_local_field :end_time %><br/>
	<%= f.label :capacity %>
	<%= f.number_field :capacity %><br/>
	<%= link_to_remove_association "Remove timeslot", f %>
</div>

app/views/events/edit.html.erb
<h1>Update details for <%= @event.name %></h1>

<%= render 'form' %>

app/views/events/index.html.erb
<ul class="example-orbit" data-orbit>
  <li class="orbit_image">
    <%= image_tag("user_browing.png")%>
  </li>
  <li class="orbit_image">
    <%= image_tag("user_browing.png")%>
  </li>
  <li class="orbit_image">
    <%= image_tag("user_browing.png")%>
  </li>
</ul>

<div class="body-margin">
  <h1 class="all-volunteering">Upcoming Volunteering Events in <span id="location">Toronto</span>

  <% if logged_in? %>
  	<span class="filter-button" id="index_filter_button">
  			<%= render 'filter_buttons' %>
  	</span>
  <% end %>
  </h1>

  <div class="events-list">
  	<%= render @events %>
  </div>
</div>

app/views/events/index.js.erb
$('.events-list').html("<%=j (render @events) %>");

app/views/events/new.html.erb
<h1>Create a new event for <%= @organization.name %></h1>

<%= render 'form' %>

app/views/events/show.html.erb
<div class="row">
  <div class="event-show small-12 large-8 columns top_title_space">
    <div class="panel callout radius">
      <div class="row">
        <div class="small-12 large-7 columns">
          <div class="event-image">
            <%= image_tag @event.event_image.url(:show) %>
          </div>
          <h1 class="event_role_margin"><%= @event.role %>
            <%= render partial: 'bookmarks/form', locals: { event: @event, bookmark: Bookmark.new } %>
          </h1>
          <% if logged_in? %>
            <% if current_user.is_authorized?(@event.organization) || current_user.admin %>

              <%= link_to "Edit Event", edit_organization_event_path(@event.organization, @event), class: "button radius" %>

              <%= button_to "Cancel Event", organization_event_path(@event.organization, @event), class: "button radius", method: "delete", data: { confirm: "Are you sure you wish to cancel this event?"} %>
            <% end %>
          <% end %>
          <h3><%= @event.name %></h3>
          <div class="event-details">
            <p><%= @event.start_time.strftime("%F %n %I:%M %p") %> - <%= @event.end_time.strftime("%I:%M %p") %></p>
          </div>
          <p><%= @event.description %></p>
          <div id="timeslot-list-show">
            <h3><strong>Book your time now</strong></h3>
            <%= render partial: 'timeslots/timeslot', collection: @event.timeslots.order(start_time: :asc) %>
          </div>
        </div>
        <div class="small-12 large-5 columns">
          <div data-latitude="<%= @event.latitude %>" data-longitude="<%= @event.longitude %>" id="event-map"> </div>
          <p class="address"><%= @event.location %></p>
          <p class="hashtags">
            <% @event.interests.each do |interest| %>
              <%="##{interest.name} "%>
            <% end %>
            <% @event.skills.each do |skill| %>
              <%="##{skill.name} "%>
            <% end %>
          </p>
          <p><%= social_share_button_tag(@event.name, :popup => "true") %></p>

        </div>
      </div>
    </div>
  </div>
  <div class="small-12 large-4 columns topspace">
    <div class="panel callout radius">
      <h3 class="event_org_name"><%= link_to @event.organization.name, organization_path(@event.organization) %></h3>
      <p><%= @event.organization.description %></p>
      <p><%= link_to "#{@event.organization.website_url}", @event.organization.website_url %></p>
      <p><%= mail_to(@event.organization.email) %></p>
      <p><%= link_to "Message the event coordinator!", new_conversation_path(:recipients => [@event.organization.event_coordinator]), class: "button radius" %></p>
    </div>
  </div>
</div>

<div class="all-arrangements small-12 large-12 columns">
  <div class="panel callout radius">
    <% if logged_in? %>
      <% if current_user.is_authorized?(@event.organization) || current_user.admin %>
        <h2><strong>View all Volunteering Arrangements for this Event</strong></h2>
        <% @event.timeslots.each do |timeslot| %>
          <ul>
            <li><h3>Volunteers for <%= timeslot.starts_at %>-<%= timeslot.ends_at %></h3></li>
            <ul>
              <% if timeslot.arrangements.any? %>
                <% timeslot.arrangements.each do |arrangement| %>
                  <li><%= "#{arrangement.user.first_name} #{arrangement.user.last_name} - Contact at:" %>
                  <%= mail_to(arrangement.user.email) %></li>
                <% end %>
              <% else %>
                <li>No volunteers for this timeslot</li>
              <% end %>
            </ul>
          </ul>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>