config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :organizations do
    resources :events, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :events, only: [:index]
  resources :events, only: [:show] do
    resources :bookmarks, only: [:create, :destroy]
  end
  resources :timeslots do
    resources :arrangements, only: [:new, :edit, :show, :create, :update, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :edit, :show, :create, :update] do
    resources :managed_organizations, only: [:index]
  end
  resources :welcomes, only: [:index]
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get '/welcome' => 'welcomes#index'
  get '/login' => 'sessions#new'
  delete '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get 'mailbox/inbox' => "mailboxes#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailboxes#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailboxes#trash", as: :mailbox_trash

end

app/controllers/mailboxes_controller.rb
class MailboxesController < ApplicationController


  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def trash
    @trash = mailbox.trash
    @active = :trash
  end

end

app/helpers/mailboxes_helper.rb
module MailboxesHelper
  def unread_messages_count
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/views/mailboxes/_folder_view.html.erb
<div class="mailbox-head large-12 columns">
  <h1>Your Messages</h1>
</div>
<div class="large-12 columns">
  <ul class="right">
    <%= link_to "New message", new_conversation_path, class: "button radius" %>
  </ul>
</div>

<div class="large-2 small-3 columns">
  <%= render 'mailboxes/folders' %>
</div>

<div class="large-10 small-9 columns">
  <% if is_conversation %>
    <%= render 'conversations/form' %>
  <% elsif messages.any? %>
    <%= render partial: 'conversations/conversation', collection: messages %>
  <% else %>
    <div class="convo-box2">
      <p>No messages to display</p>
    </div>
  <% end %>
</div>

app/views/mailboxes/_folders.html.erb
 <ul class="icon-bar vertical three-up">
  <li class="<%= active_page(:inbox) %> item">
    <%= link_to mailbox_inbox_path do  %>
      <span>Inbox</span>
    <% end %>
  </li>

  <li class="<%= active_page(:sent) %> item">
    <%= link_to mailbox_sent_path do  %>
      <span>Sent</span>
    <% end %>
  </li>

  <li class="<%= active_page(:trash) %> item">
    <%= link_to mailbox_trash_path do  %>
      <span>Trash</span>
    <% end %>
  </li>
</ul>

app/views/mailboxes/inbox.html.erb
<%= render partial: 'mailboxes/folder_view', locals: { is_conversation: false, messages: @inbox } %>

app/views/mailboxes/sent.html.erb
<%= render partial: 'mailboxes/folder_view', locals: { is_conversation: false, messages: @sent } %>

app/views/mailboxes/trash.html.erb
<%= render partial: 'mailboxes/folder_view', locals: { is_conversation: false, messages: @trash } %>