config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :organizations do
    resources :events, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :events, only: [:index]
  resources :events, only: [:show] do
    resources :bookmarks, only: [:create, :destroy]
  end
  resources :timeslots do
    resources :arrangements, only: [:new, :edit, :show, :create, :update, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :edit, :show, :create, :update] do
    resources :managed_organizations, only: [:index]
  end
  resources :welcomes, only: [:index]
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get '/welcome' => 'welcomes#index'
  get '/login' => 'sessions#new'
  delete '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get 'mailbox/inbox' => "mailboxes#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailboxes#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailboxes#trash", as: :mailbox_trash

end

app/models/organization.rb
class Organization < ActiveRecord::Base
	has_many :events
	belongs_to :event_coordinator, class_name: "User", foreign_key: "user_id"
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]
  before_action :get_organization, only: [:show]

  # Organization actions will become relevant if we allow a user to create organizations

  # def new
  #   @organization = Organization.new
  # end

  # def create
  #   @organization = Organization.new(org_params)
  #   if @organization.save
  #     OrganizationMailer.welcome_email(@organization).deliver_later
  #     puts "successful"
  #   else
  #     puts "unsuccessful"
  #   end
  # end

  def edit
  end

  def update
  end

  def index
  end

  def destroy
  end

  def show
  end

  private

  def get_organization
    @organization = Organization.find(params[:id])
  end

  def org_params
    params.require(:organization).permit(:name, :email, :website_url, :description)
  end

end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/show.html.erb
<div class="org-show">
  <h1>Organization: <%= @organization.name %></h1>
  <p>Email: <%= @organization.email %></p>
  <p>Website: <a href="<%= @organization.website_url %>"><%= @organization.website_url %></a></p>
  <p>Description: <%= @organization.description %></p>
  <% if logged_in? %>
    <% if current_user.is_authorized?(@organization) || current_user.admin %>
     <%= button_to "Create an Event", new_organization_event_path(@organization), class: "button radius", method: "get" %>
    <% end %>
  <% end %>
</div>

<div class="org-events">
  <h2>Current Volunteering Events</h2>
  <!-- Should the below use another partial? -->
  <% @organization.events.each do |event| %>
    <h3>Name: <%= link_to "#{event.name}", event_path(event) %></h3>
    <p>Location:<%= event.location %></p>
    <p>Date: <%= event.start_time.strftime("%A, %m/%d/%y") %>
    <% if logged_in? %>
      <% if current_user.is_authorized?(event.organization) || current_user.admin %>
        <%= button_to "Edit Event", edit_organization_event_path(event.organization, event), class: "button radius", method: "get" %>
      <% end %>
    <% end %>
  <% end %>
</div>